export const UserActions = {
  ACCEPT_FR: 'accept_fr',
  APPLY_JOB: 'apply_job',
  BUY_ITEM: 'buy_item',
  COLLECT_REWARDS: 'collect_rewards',
  CREATE_THREAD: 'create_thread',
  DECLINE_FR: 'decline_fr',
  DELETE_ALERT: 'delete_alert',
  DONATE: 'donate',
  GIFT: 'gift',
  HEAL: 'heal',
  LEVEL_UP: 'level_up',
  LIKE_SHOUT: 'like_shout',
  READ_ALERT: 'read_alert',
  REMOVE_FRIEND: 'remove_friend',
  SEND_FR: 'send_fr',
  SEND_SHOUT: 'send_shout',
  TRAIN: 'train',
  TRAVEL: 'travel',
  UNLIKE_SHOUT: 'unlike_shout',
  UPDATE_DESC: 'update_desc',
  UPDATE_NAME: 'update_name',
  UPDATE_PW: 'update_pw',
  UPLOAD_PFP: 'upload_pfp',
  WORK: 'work',
}

export const CompanyActions = {
  CREATE_JOB: 'create_job',
  CREATE_PRODUCT: 'create_product',
  DELETE_COMP: 'delete_comp',
  DELETE_JOB: 'delete_job',
  DELETE_PRODUCT: 'delete_product',
  DEPOSITE_FUNDS: 'deposit_funds',
  EDIT_EMPLOYEE: 'edit_employee',
  EDIT_JOB: 'edit_job',
  EDIT_PRODUCT: 'edit_product',
  FIRE_EMPLOYEE: 'fire_employee',
  RELOCATE: 'relocate',
  SELL_COMP: 'sell_comp',
  UPDATE_NAME: 'update_name',
  UPLOAD_LOGO: 'upload_logo',
  WITHDRAW_FUNDS: 'withdraw_funds',
}