name: Cleanup CP Elections Job
on:
  schedule:
    - cron: '0 0 6 * *'
jobs:
  terminate-prod:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl --request POST \
          --url '${{ secrets.APP_URL }}/api/cron/elections/country/terminate' \
          --header 'Authorization: Bearer ${{ secrets.ACTIONS_KEY }}'
  create-prod:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl --request POST \
          --url '${{ secrets.APP_URL }}/api/cron/elections/country/create' \
          --header 'Authorization: Bearer ${{ secrets.ACTIONS_KEY }}'  
  terminate-dev:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl --request POST \
          --url '${{ secrets.APP_DEV_URL }}/api/cron/elections/country/terminate' \
          --header 'Authorization: Bearer ${{ secrets.ACTIONS_KEY }}'
  create-dev:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl --request POST \
          --url '${{ secrets.APP_DEV_URL }}/api/cron/elections/country/create' \
          --header 'Authorization: Bearer ${{ secrets.ACTIONS_KEY }}'